name: Hello World Example

on: 
  workflow_dispatch:  # nothing here means "manual" (could also be "commit")

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World Step
        run: echo 'Hello World' # weird that no dash is here; are "name" and "run" both sub-items of a single step? 
